//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaEncyclopediaInUrdu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileID { get; set; }
        public string ContactNumber { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string LicenseNumber { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public string Type { get; set; }
        public string ImagePath { get; set; }
    }
}
